### ISSUE TITLE
Painel Excelente.

### ISSUE THREAD

**Issue by Kiny-Kiny** [Isqneeh/GrabberTool#1]
Caramba, curti muito o painel de vocês, eu tenho o meu próprio que também é Open Source. Vcs tem Whatsapp pra gente trocar uma idéia? :]

**Comment by mdsdias** [comment]
Opa meu amigo, perdão o tempo de resposta.
Curti muito seu painel.
Sim, tenho um whatsapp, te dei um oi lá ;)

**Comment by Kiny-Kiny** [comment]
Caramba, obg, mas qual é teu número? Tem muita gente me chamando kkkkk

**Comment by mdsdias** [comment]
Kk é um com a mesma foto do meu perfil, _Vou falar melhor com vc lá já já ;)_
